
/**
 * Questions as String[] instead of files since cannot read files online.
 */
public class File {
    public static final String[] MATH_TRIVIA = {
            "# Single Round",
            "# Category format = :CATX:Category name, where X is the catgory number.",
            "# Question format = :QUESTX:$:Question test, where X is the question number",
            "#     and $ is the value displayed for the question.",
            "# Questions are linked to categories in groups of 5. For example, questions 1",
            "#     to 5 are in category 1, questions 6 to 10 in category 2, and so on.",
            "# Answer format = :ANSWERX:T/F:Answer text, where X is the question number and",
            "#     T/F is either T (for true) or F (for false). Answers are optional.",
            "# Answer order format = :ANSWERORDER1:randomized to shuffle the answers. Skip",
            "#     this statement if you do not wnat to randomize answers.",
            "# Explanation format = :EXPLANATIONX:Explanation text, where X is the question",
            "#     number. Note that you can force new lines using \n.",
            "",

            ":CAT1:ABSOULTE\nVALUE",
            "",
            ":QUEST1:100:The absolute value of |0| is..",
            ":ANSWER1:T:0",
            ":ANSWER1:F:None of the above",
            ":ANSWER1:F:Not applicable",
            ":ANSWER1:F:|0|",
            ":ANSWERORDER1:randomized",
            ":EXPLANATION1:The distance from of a number from 0 without its sign.",
            "",
            ":QUEST2:200:The absolute value of -|-2| is..",
            ":ANSWER2:T:-2",
            ":ANSWER2:F:2",
            ":ANSWER2:F:|-2|",
            ":ANSWER2:F:None of the above",
            ":ANSWERORDER2:randomized",
            ":EXPLANATION2:We know |-2| is 2, so -|-2| is -2. ",
            "",
            ":QUEST3:300:The absolute value of |-5|+|2| is..",
            ":ANSWER3:T:7",
            ":ANSWER3:F:-3",
            ":ANSWER3:F:-|7|",
            ":ANSWER3:F:None of the above",
            ":ANSWERORDER3:randomized",
            ":EXPLANATION3:The abs value of |-5| is 5, and |2| is 2 so 5+2= 7",
            "",
            ":QUEST4:400: The absolute value of|-3*5| is ...",
            ":ANSWER4:T:15",
            ":ANSWER4:F:|15|",
            ":ANSWER4:F:|-15|",
            ":ANSWER4:F:None of the above",
            ":ANSWERORDER4:randomized",
            ":EXPLANATION4:If |-3*5| is |-15|, the abs value is 15.",
            "",
            ":QUEST5:500:Arrange from greatest to least (|4|,|1|,|0|,-|-21|,|-2|)",
            ":ANSWER5:T:0,1,2,4,-21",
            ":ANSWER5:F:21,4,2,1,0",
            ":ANSWER5:F:-21,0,1,2,4",
            ":ANSWER5:F:None of the above",
            ":ANSWERORDER5:randomized",
            ":EXPLANATION5:",
            "",
            ":CAT2:PERFECT\nSQUARE",
              "",
            ":QUEST6:100:What is the square root of 4?",
            ":ANSWER6:T:2",
            ":ANSWER6:F:4",
            ":ANSWER6:F:1",
            ":ANSWER6:F:None of these.",
            ":ANSWERORDER6:randomized",
            ":EXPLANATION6:if 2x2=4, then the square root of 4 is 2",
            "",
            ":QUEST7:200:What is the square root of 9?",
            ":ANSWER7:T:3",
            ":ANSWER7:F:-9",
            ":ANSWER7:F:4.5",
            ":ANSWER7:F:None of these",
            ":ANSWERORDER7:randomized",
            ":EXPLANATION7:if 3x3=9, then the square root of 9 is 3",
            "",
            ":QUEST8:300:What is the square root of 100?",
            ":ANSWER8:T:10",
            ":ANSWER8:F:20",
            ":ANSWER8:F:100",
            ":ANSWER8:F:None of these.",
            ":ANSWERORDER8:randomized",
            ":EXPLANATION8:if 10x10=100, then the square root of 100 is 10",
            "",
            ":QUEST9:400:What is the square root of 144?",
            ":ANSWER9:T:12",
            ":ANSWER9:F:14",
            ":ANSWER9:F:144",
            ":ANSWER9:F:None of these",
            ":ANSWERORDER9:randomized",
            ":EXPLANATION9:if 12x12=144, then the square root of 114 is 12",
            "",
            ":QUEST10:500:What is the square root of 400?",
            ":ANSWER10:T:20",
            ":ANSWER10:F:14",
            ":ANSWER10:F:40",
            ":ANSWER10:F:None of these",
            ":ANSWERORDER10:randomized",
            ":EXPLANATION10:if 20x20=400, then the square root of 400 is 20",

            ":CAT3:COMPARE\nRATIONAL\nNUMBERS",

            "",
            ":QUEST11:100: -8 _ -11",
            ":ANSWER11:T: >",
            ":ANSWER11:F: <",
            ":ANSWER11:F: =",
            ":ANSWER11:F: None of These",
            ":ANSWERORDER11:randomized",
            ":EXPLANATION11: -8 is greater than (>) -11",
            "",
            ":QUEST12:200: 1/8 _ 1/10",
            ":ANSWER12:T: >",
            ":ANSWER12:F: <",
            ":ANSWER12:F: =",
            ":ANSWER12:F: None of These",
            ":ANSWERORDER12:randomized",
            ":EXPLANATION12: 1/8 is greater than (>) -11",
            "",
            ":QUEST13:300: What is the value of 3x-1 when x is equal to 10?",
            ":ANSWER13:T: None of These",
            ":ANSWER13:F: 22",
            ":ANSWER13:F: -29",
            ":ANSWER13:F: 0.29",
            ":ANSWERORDER13:randomized",
            ":EXPLANATION13: 3(10) - 1 = 30 - 1, this equals 16",
            "",
            ":QUEST14:400: is 0.5% greater than 0.45? ",
            ":ANSWER14:T: False",
            ":ANSWER14:F: True",
            ":ANSWERORDER14:randomized",
            ":EXPLANATION14: 0.5% in decimal form is 0.005, which is less than 0.45 ",
            "",
            ":QUEST15:500: What is the value of 2x + 4y when x is equal to 2 and y is equal to 3? ",
            ":ANSWER15:T: 16",
            ":ANSWER15:F: 24",
            ":ANSWER15:F: 61",
            ":ANSWER15:F: None of These",
            ":ANSWERORDER15:randomized",
            ":EXPLANATION15: 2(2) + 4(3) = 4 + 12, this equals 16",
            "",

            ":CAT4:PROBLEMS\nWITH\nRATIONAL NUM",

            "",
            ":QUEST16:100:It's the sum total of the degrees in a circle.",
            ":ANSWER16:T:360",
            ":ANSWER16:F:180",
            ":ANSWER16:F:2\u00B7\u03C0\u00B7r",
            ":ANSWER16:F:\u03C0\u00B7r\u00B2",
            ":ANSWERORDER16:randomized",
            ":EXPLANATION16:There are 360 degrees in a circle.",
            "",
            ":QUEST17:200:For an Actor, zero degrees is in this direction of the compass.",
            ":ANSWER17:F:to the north",
            ":ANSWER17:T:to the east",
            ":ANSWER17:F:to the south",
            ":ANSWER17:F:to the west",
            "#:ANSWERORDER17:randomized",
            ":EXPLANATION17:Zero degrees is to the east and the angle of the circle increases clockwise.",
            "",
            ":QUEST18:300:To find the current orientation (or heading) of an actor, use this method of the Actor class.",
            ":ANSWER18:T:getRotation()",
            ":ANSWER18:F:getOrientation()",
            ":ANSWER18:F:getHeading()",
            ":ANSWER18:F:getDirection()",
            ":ANSWERORDER18:randomized",
            ":EXPLANATION18:The getRotation() method of the Actor class returns the current rotation of the object. Rotation is a degree value in the range of (0..359). Zero degrees is to the east and the angle increases clockwise.",
            "",
            ":QUEST19:400:To turn an actor facing straight up (or north), use this command.",
            ":ANSWER19:T:setRotation(270)",
            ":ANSWER19:F:setRotation(0)",
            ":ANSWER19:F:setRotation(\"north\")",
            ":ANSWER19:F:setRotation(\"up\")",
            ":ANSWERORDER19:randomized",
            ":EXPLANATION19:Zero degrees is to the east and the angle of the circle increases clockwise. Straight up, or north, is at 270 degrees. Use the setRotation() method to set the orientation (or heading) of an Actor.",
            "",
            ":QUEST20:500:To turn an actor 10 degress clockwise from their current heading, use this command.",
            ":ANSWER20:T:turn(10)",
            ":ANSWER20:F:turn(-10)",
            ":ANSWER20:F:setRotation(+10)",
            ":ANSWER20:F:setRotation(-10)",
            ":ANSWERORDER20:randomized",
            ":EXPLANATION20:Zero degrees is to the east and the angle of the circle increases clockwise. Straight up, or north, is at 270 degrees. To turn clockwise use a positive number.",
            "",

            ":CAT5:POWER OF 10\nEXPONENTS",

            "",
            ":QUEST21:100:Write 2^-1 as a decimal number.",
            ":ANSWER21:T:0.5",
            ":ANSWER21:F:0.05",
            ":ANSWER21:F:-2",
            ":ANSWER21:F:-0.5",
            ":ANSWERORDER21:randomized",
            ":EXPLANATION21:2^-1 = 0.5 because...",
            "",
            ":QUEST22:200:Write 10^-5 as a decimal number.",
            ":ANSWER22:T:0.00001",
            ":ANSWER22:F:0.000001",
            ":ANSWER22:F:0.0001",
            ":ANSWER22:F:-0.00001",
            ":ANSWERORDER22:randomized",
            ":EXPLANATION22:10^-5 = 0.00001 because...",
            "",
            ":QUEST23:300:Write 10^-1 as a decimal number.",
            ":ANSWER23:F:0.01",
            ":ANSWER23:F:-0.01",
            ":ANSWER23:T:0.1",
            ":ANSWER23:F:0.01",
            ":ANSWER23:F:-0.1",
            ":ANSWERORDER23:randomized",
            ":EXPLANATION23:10^-1 = 0.1 because...",
            "",
            ":QUEST24:400:Write 5^-1 as a decimal number.",
            ":ANSWER24:T:0.2",
            ":ANSWER24:F:0.5",
            ":ANSWER24:F:0.02",
            ":ANSWER24:F:-0.5",
            ":ANSWER24:F:-0.2",
            ":ANSWER24:F:-0.5",
            ":ANSWERORDER24:randomized",
            ":EXPLANATION24:5^-1 = 0.2 because...",
            "",
            ":QUEST25:500:Write 10^10 as a decimal number.",
            ":ANSWER25:T:10000000000",
            ":ANSWER25:F:1000000000",
            ":ANSWER25:F:100000000000",
            ":ANSWER25:F:100000000",
            ":ANSWERORDER25:randomized",
            ":EXPLANATION25:The expression:10^10 = 10000000000 because...",
            "", 

            ":CAT6:SCIENTIFIC\nNOTATION",

            "",
            ":QUEST26:100:This test condition says that: x is positive.",
            ":ANSWER26:T:x > 0",
            ":ANSWER26:F:0 > x",
            ":ANSWER26:F:x < 0",
            ":ANSWER26:F:x >= 0",
            ":ANSWERORDER26:randomized",
            ":EXPLANATION26:A positive number is a number greater than zero. The relational operator > means greater than. So the expression (x > 0) means x is positive.",
            "",
            ":QUEST27:200:This test condition says: x is negative.",
            ":ANSWER27:T:x < 0",
            ":ANSWER27:F:x > 0",
            ":ANSWER27:F:0 > x",
            ":ANSWER27:F:x >= 0",
            ":ANSWERORDER27:randomized",
            ":EXPLANATION27:A negative number is a number less than zero. The relational operator < means: less than. So the expression (x < 0) means: x is negative.",
            "",
            ":QUEST28:300:This test condition says that x is zero.",
            ":ANSWER28:T:x == 0",
            ":ANSWER28:F:x = 0",
            ":ANSWER28:F:0 = x",
            ":ANSWER28:F:x is 0",
            ":ANSWERORDER28:randomized",
            ":EXPLANATION28:The equality operator is \"==\" (two equal signs). So the expression (x == 0) means: x is zero.",
            "",
            ":QUEST29:400:This test condition says that x is not equal to y.",
            ":ANSWER29:T:x != y",
            ":ANSWER29:F:x <> y",
            ":ANSWER29:F:x =! y",
            ":ANSWER29:F:x \u2260 y",
            ":ANSWERORDER29:randomized",
            ":EXPLANATION29:The algebra symbol \u2260 is not easy to make on a standard keyboard. Thus two symbols are used for inequality: !=. Code the symbols in the order people normally say them.",
            "",
            ":QUEST30:500:This test condition says that x is greater than y + 1.",
            ":ANSWER30:T:x > y + 1",
            ":ANSWER30:F:x + y = 1",
            ":ANSWER30:F:x < y + 1",
            ":ANSWER30:F:x + 1 > y",
            ":ANSWERORDER30:randomized",
            ":EXPLANATION30:Each operand (side of the operator) can be an arithmetic expression. The arithmetic is preformed before the comparison is made.",
            "",
            ""
        };


        }


